name: simple-bank

services:
  postgres:
    image: postgres:16rc1-alpine3.18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=simple_bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d simple_bank -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_SOURCE=postgresql://root:1234@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy